# Site settings
title: 
header-img: img/home-bg.png
email: tscotce@gmail.com
copyright_name: tscotce
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: TatyanaScotce
github_username:  tscotce
learn_profile: tscotce
email_username: tscotce@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
