# Site settings
author: Tatyana Celovsky
title: Coding Adventures
header-img: img/home-bg.png
email: tatyana.celovsky@gmail.com
copyright_name: Tatyana Celovsky
description: > # this means to ignore newlines until "baseurl:"
  Let's go on a coding adventure!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: TatyanaCelovsky
github_username:  tcelovsky

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
